version: "3.9"

services:
  app:
    image: dockerhubalancarvalho/fiap-videoslice-svc-engine:0.0.1
    container_name: videoslice_app
    restart: "no"
    environment:
      "videoslice.integration.sqs.sqsEndpoint": "http://localhost:4566"
      "videoslice.integration.s3.s3Endpoint": "http://localhost:4566"
      "videosliceapi.integration.aws.overrideAwsEndpoint": "http://localhost:4566"

      "videoslice.integration.sqs.videosToBeProcessedQueueName": "videoslice_job_requests"
      "videoslice.integration.sqs.videosToBeProcessedQueueUrl": "http://localhost:4566/000000000000/videoslice_job_requests"
      "videoslice.integration.sqs.videoStatusQueueName": "videoslice_job_status"
      "videoslice.integration.sqs.videoStatusQueueUrl": "http://localhost:4566/000000000000/videoslice_job_status"

      "videoslice.integration.s3.bucketName": "videoslice-job-requests"

    ports:
      - "8090:8090"
    depends_on:
      db:
        condition: service_healthy
      mongodb:
        condition: service_healthy

