apiVersion: v1
kind: Service
metadata:
  name: archburgers-app-svc
spec:
  type: NodePort
  selector:
    app: archburgers-app
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
      nodePort: 30080
