apiVersion: apps/v1
kind: Deployment
metadata:
  name: videoslice-svc-engine-deployment
spec:
  selector:
    matchLabels:
      app: videoslice-svc-engine
  replicas: 1
  template:
    metadata:
      labels:
        app: videoslice-svc-engine
    spec:
      containers:
        - name: videoslice-engine-app-container
          image: dockerhubalancarvalho/fiap-videoslice-svc-engine:0.0.1
          ports:
            - containerPort: 8091
          env:
            - name: "videoslice.integration.sqs.sqsEndpoint"
              valueFrom:
                configMapKeyRef:
                  name: "videoslice-aws-config"
                  key: "videoslice.integration.sqs.sqsEndpoint"
            - name: "videoslice.integration.s3.s3Endpoint"
              valueFrom:
                configMapKeyRef:
                  name: "videoslice-aws-config"
                  key: "videoslice.integration.s3.s3Endpoint"
            - name: "videosliceapi.integration.aws.overrideAwsEndpoint"
              valueFrom:
                configMapKeyRef:
                  name: "videoslice-aws-config"
                  key: "videosliceapi.integration.aws.overrideAwsEndpoint"
            - name: "videoslice.integration.sqs.videosToBeProcessedQueueName"
              valueFrom:
                configMapKeyRef:
                  name: "videoslice-aws-config"
                  key: "videoslice.integration.sqs.videosToBeProcessedQueueName"
            - name: "videoslice.integration.sqs.videosToBeProcessedQueueUrl"
              valueFrom:
                configMapKeyRef:
                  name: "videoslice-aws-config"
                  key: "videoslice.integration.sqs.videosToBeProcessedQueueUrl"
            - name: "videoslice.integration.sqs.videoStatusQueueName"
              valueFrom:
                configMapKeyRef:
                  name: "videoslice-aws-config"
                  key: "videoslice.integration.sqs.videoStatusQueueName"
            - name: "videoslice.integration.sqs.videoStatusQueueUrl"
              valueFrom:
                configMapKeyRef:
                  name: "videoslice-aws-config"
                  key: "videoslice.integration.sqs.videoStatusQueueUrl"
            - name: "videoslice.integration.s3.bucketName"
              valueFrom:
                configMapKeyRef:
                  name: "videoslice-aws-config"
                  key: "videoslice.integration.s3.bucketName"

            # Needs to be passed via env var - Pod cannot assume role in AwsAcademy
            - name: "AWS_ACCESS_KEY_ID"
              valueFrom:
                configMapKeyRef:
                  name: "videoslice-aws-config"
                  key: "videoslice.integration.aws.AWS_ACCESS_KEY_ID"
            - name: "AWS_SECRET_ACCESS_KEY"
              valueFrom:
                configMapKeyRef:
                  name: "videoslice-aws-config"
                  key: "videoslice.integration.aws.AWS_SECRET_ACCESS_KEY"
            - name: "AWS_SESSION_TOKEN"
              valueFrom:
                configMapKeyRef:
                  name: "videoslice-aws-config"
                  key: "videoslice.integration.aws.AWS_SESSION_TOKEN"
          resources:
            requests:
              cpu: 250m


