apiVersion: v1
kind: Service
metadata:
  name: videoslice-svc-engine-service
spec:
  type: NodePort
  selector:
    app: videoslice-svc-engine
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
      nodePort: 30080
