apiVersion: apps/v1
kind: Deployment
metadata:
  name: archburgers-app-deployment
spec:
  selector:
    matchLabels:
      app: archburgers-app
  replicas: 1
  template:
    metadata:
      labels:
        app: archburgers-app
    spec:
      containers:
        - name: archburgers-app-container
          image: dockerhubalancarvalho/architect-burgers-pagamentos:0.0.7
          ports:
            - containerPort: 8090
          env:

            - name: "archburgers.integration.aws.region"
              valueFrom:
                configMapKeyRef:
                  name: "archburgers-aws-config"
                  key: "archburgers.integration.aws.region"
            - name: "archburgers.integration.sqs.pagamentosEmAbertoQueueName"
              valueFrom:
                configMapKeyRef:
                  name: "archburgers-aws-config"
                  key: "archburgers.integration.sqs.pagamentosEmAbertoQueueName"
            - name: "archburgers.integration.sqs.pagamentosEmAbertoQueueUrl"
              valueFrom:
                configMapKeyRef:
                  name: "archburgers-aws-config"
                  key: "archburgers.integration.sqs.pagamentosEmAbertoQueueUrl"
            - name: "archburgers.integration.sqs.pagamentosConcluidosQueueName"
              valueFrom:
                configMapKeyRef:
                  name: "archburgers-aws-config"
                  key: "archburgers.integration.sqs.pagamentosConcluidosQueueName"
            - name: "archburgers.integration.sqs.pagamentosConcluidosQueueUrl"
              valueFrom:
                configMapKeyRef:
                  name: "archburgers-aws-config"
                  key: "archburgers.integration.sqs.pagamentosConcluidosQueueUrl"
            - name: "archburgers.integration.sqs.sqsEndpoint"
              valueFrom:
                configMapKeyRef:
                  name: "archburgers-aws-config"
                  key: "archburgers.integration.sqs.sqsEndpoint"

            # Needs to be passed via env var - Pod cannot assume role in AwsAcademy
            - name: "AWS_ACCESS_KEY_ID"
              valueFrom:
                configMapKeyRef:
                  name: "archburgers-aws-config"
                  key: "archburgers.integration.aws.AWS_ACCESS_KEY_ID"
            - name: "AWS_SECRET_ACCESS_KEY"
              valueFrom:
                configMapKeyRef:
                  name: "archburgers-aws-config"
                  key: "archburgers.integration.aws.AWS_SECRET_ACCESS_KEY"
            - name: "AWS_SESSION_TOKEN"
              valueFrom:
                configMapKeyRef:
                  name: "archburgers-aws-config"
                  key: "archburgers.integration.aws.AWS_SESSION_TOKEN"
          resources:
            requests:
              cpu: 250m


